# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

User.destroy_all
Channel.destroy_all


lol = Channel.create!(name: 'League of Legends', pic_url: 'https://static-cdn.jtvnw.net/ttv-boxart/League%20of%20Legends-285x380.jpg')
creative = Channel.create!(name: 'Creative', pic_url: 'https://static-cdn.jtvnw.net/ttv-boxart/Creative-285x380.jpg')
ow = Channel.create!(name: 'Overwatch', pic_url: 'https://static-cdn.jtvnw.net/ttv-boxart/Overwatch-285x380.jpg')
pubg = Channel.create!(name: "PLAYERUNKNOWN'S BATTLEGROUNDS", pic_url: 'https://static-cdn.jtvnw.net/ttv-boxart/PLAYERUNKNOWN%27S%20BATTLEGROUNDS-285x380.jpg')
hs = Channel.create!(name: 'Hearthstone', pic_url: 'https://static-cdn.jtvnw.net/ttv-boxart/Hearthstone-285x380.jpg')
dota = Channel.create!(name: 'Dota 2', pic_url: 'https://static-cdn.jtvnw.net/ttv-boxart/Dota%202-285x380.jpg')
music = Channel.create!(name: 'Music', pic_url: 'https://static-cdn.jtvnw.net/ttv-boxart/Music-285x380.jpg')
csgo = Channel.create!(name: 'Counter-Strike: Global Offensive', pic_url: 'https://static-cdn.jtvnw.net/ttv-boxart/Counter-Strike:%20Global%20Offensive-285x380.jpg')
wow = Channel.create!(name: 'World of Warcraft', pic_url: 'https://static-cdn.jtvnw.net/ttv-boxart/World%20of%20Warcraft-285x380.jpg')
mc = Channel.create!(name: 'Minecraft', pic_url: 'https://static-cdn.jtvnw.net/ttv-boxart/Minecraft-285x380.jpg')
poe = Channel.create!(name: 'Path of Exile', pic_url: 'https://static-cdn.jtvnw.net/ttv-boxart/Path%20of%20Exile-285x380.jpg')
smo = Channel.create!(name: 'Super Mario Odyssey', pic_url: 'https://static-cdn.jtvnw.net/ttv-boxart/Super%20Mario%20Odyssey-285x380.jpg')
botw = Channel.create!(name: 'The Legend of Zelda: Breath of the Wild', pic_url: 'https://static-cdn.jtvnw.net/ttv-boxart/The%20Legend%20of%20Zelda:%20Breath%20of%20the%20Wild-285x380.jpg')
smite = Channel.create!(name: 'Smite', pic_url: 'https://static-cdn.jtvnw.net/ttv-boxart/Smite-285x380.jpg')
rss = Channel.create!(name: "Tom Clancy's Rainbow Six: Siege", pic_url: 'https://static-cdn.jtvnw.net/ttv-boxart/Tom%20Clancy%27s%20Rainbow%20Six:%20Siege-285x380.jpg')
rl = Channel.create!(name: 'Rocket League', pic_url: 'https://static-cdn.jtvnw.net/ttv-boxart/Rocket%20League-285x380.jpg')
ssb4 = Channel.create!(name: 'Super Smash Bros. for Wii U', pic_url: 'https://static-cdn.jtvnw.net/ttv-boxart/Super%20Smash%20Bros.%20for%20Wii%20U-285x380.jpg')
ssbm = Channel.create!(name: 'Super Smash Bros. Melee', pic_url: 'https://static-cdn.jtvnw.net/ttv-boxart/Super%20Smash%20Bros.%20Melee-285x380.jpg')
oot = Channel.create!(name: 'The Legend of Zelda: Ocarina of Time', pic_url: 'https://static-cdn.jtvnw.net/ttv-boxart/The%20Legend%20of%20Zelda:%20Ocarina%20of%20Time-285x380.jpg')

demo = User.create!(username: 'guest', password: 'password', stream_title: 'Good job finding this!', stream_url: '')
lol1 = User.create!(username: 'LoLUnofficial', password: 'pqiuwrbgpas', channel_id: lol.id, stream_title: '2017 Worlds Stage', stream_url: 'http://player.twitch.tv/?video=187649386&time=01h09m15s')
lol2 = User.create!(username: 'lidlid', password: 'osduaczhfj', channel_id: lol.id, stream_title: 'side account', stream_url: 'http://player.twitch.tv/?video=204800797&time=10m45s')
lol3 = User.create!(username: 'dayrus', password: 'pqiuwrbgpas', channel_id: lol.id, stream_title: 'solo queue', stream_url: 'http://player.twitch.tv/?video=204860635&time=01h52m50s')
art1 = User.create!(username: 'RobBoss', password: 'ksdvnb;asd', channel_id: creative.id, stream_title: 'Happy Little Accidents', stream_url: 'http://player.twitch.tv/?video=187283482&time=03m46s')
art2 = User.create!(username: 'Foodie', password: 'paasdhw-hqp', channel_id: creative.id, stream_title: 'All cooking, all the time', stream_url: 'http://player.twitch.tv/?channel=food')
art3 = User.create!(username: 'Saynayer', password: 'yesjfdok', channel_id: creative.id, stream_title: 'Compiler debugging and simplification', stream_url: 'http://player.twitch.tv/?video=204658747&time=01h01m15s')
ovw1 = User.create!(username: 'albatross', password: 'qoweurmc3098m4qcpiwj', channel_id: ow.id, stream_title: 'gametime', stream_url: 'http://player.twitch.tv/?video=182600540&time=14m52s')
ovw2 = User.create!(username: 'sunsun', password: 'tejsritdyas', channel_id: ow.id, stream_title: 'monday', stream_url: 'http://player.twitch.tv/?video=204738688&time=01h10m30s')
ovw3 = User.create!(username: 'OWTournaments', password: 'yjhfdjhgerqjdfafk', channel_id: ow.id, stream_title: 'AOC Malta Cyber Series', stream_url: 'http://player.twitch.tv/?video=97152539&time=36m20s')
pub1 = User.create!(username: 'SurgeonRespect', password: 'qo43yxrmoiurhmc', channel_id: pubg.id, stream_title: 'Domination', stream_url: 'http://player.twitch.tv/?video=203488645&time=01h56m56s')
pub2 = User.create!(username: 'cloak', password: 'hrguhaposdjf', channel_id: pubg.id, stream_title: 'what', stream_url: 'http://player.twitch.tv/?video=204810984&time=02h36m20s')
pub3 = User.create!(username: 'ESL_PUBG', password: 'hytrsjeikrjgn', channel_id: pubg.id, stream_title: 'IEM Oakland PUBG Invitational', stream_url: 'http://player.twitch.tv/?video=202496758&time=07m10s')
hts1 = User.create!(username: 'Kibles', password: 'msldfhgioveuhc', channel_id: hs.id, stream_title: 'thanksgiving stream', stream_url: 'http://player.twitch.tv/?video=204812454&time=28m34s')
hts2 = User.create!(username: 'Tramp', password: 'aewiojfdifgs', channel_id: hs.id, stream_title: 'its a miracle', stream_url: 'http://player.twitch.tv/?video=205070889&time=19m14s')
hts3 = User.create!(username: 'Scamaz', password: 'hgurdsljdf', channel_id: hs.id, stream_title: '12 win arenas', stream_url: 'http://player.twitch.tv/?video=204987368&time=26m12s')
dot1 = User.create!(username: 'BeforeTheSummit', password: 'ocmsdvgsjclk;', channel_id: dota.id, stream_title: 'SEA qualifiers - Fnatic vs Fire Dragoon', stream_url: 'http://player.twitch.tv/?video=204932299&time=38m32s')
dot2 = User.create!(username: 'WhiteDotA', password: 'wqrhdsfgasef;', channel_id: dota.id, stream_title: 'DotA2', stream_url: 'http://player.twitch.tv/?video=200730905&time=31m45s')
dot3 = User.create!(username: 'bebebe', password: 'gjregsdfghj;', channel_id: dota.id, stream_title: 'Ranked shenanigans', stream_url: 'http://player.twitch.tv/?video=204431194&time=31m01s')
mus1 = User.create!(username: 'Monsterdog', password: 'asdjfasdlfkasjf', channel_id: music.id, stream_title: '24/7 EDM', stream_url: 'http://player.twitch.tv/?channel=monstercat')
mus2 = User.create!(username: 'deadmau5', password: 'yhodshkjlsk', channel_id: music.id, stream_title: 'studio work', stream_url: 'http://player.twitch.tv/?video=202062913&time=20m10s')
mus3 = User.create!(username: 'danielcronson', password: 'yhlsdfjgnjsfdk', channel_id: music.id, stream_title: 'Improv', stream_url: 'http://player.twitch.tv/?video=205092084&time=18m20s')
cgo1 = User.create!(username: 'ESL_CSGO', password: 'tuhsetjdhfj', channel_id: csgo.id, stream_title: 'C9vs NaVi', stream_url: 'http://player.twitch.tv/?video=204240174&time=12h40m20s')
cgo2 = User.create!(username: 'shout', password: 'gyyfhdfngdw', channel_id: csgo.id, stream_title: 'making global', stream_url: 'http://player.twitch.tv/?video=183205964&time=56m38s')
cgo3 = User.create!(username: 'blastpro', password: 'lkjgcdtrf', channel_id: csgo.id, stream_title: 'Pro Series', stream_url: 'http://player.twitch.tv/?video=204159679&time=2h35m10s')
wow1 = User.create!(username: 'asmonsilver', password: 'gkdhjfvk', channel_id: wow.id, stream_title: 'Project 70', stream_url: 'http://player.twitch.tv/?video=204502220&time=01h53m10s')
wow2 = User.create!(username: 'beera', password: 'hjsduhbnsldkgjg', channel_id: wow.id, stream_title: 'Vanilla', stream_url: 'http://player.twitch.tv/?video=200735440&time=01m46s')
wow3 = User.create!(username: 'towel', password: 'kgvhjcdtrfs', channel_id: wow.id, stream_title: 'Antorus raid!', stream_url: 'http://player.twitch.tv/?video=204958889&time=03h13m50s')
mnc1 = User.create!(username: 'waffle', password: 'jhgdxfbcf', channel_id: mc.id, stream_title: 'speedrun', stream_url: 'http://player.twitch.tv/?video=48057726&time=17m50s')
mnc2 = User.create!(username: 'ungespielt', password: 'fgnslkjdhfljsfd', channel_id: mc.id, stream_title: 'Craft attack mit der crew', stream_url: 'http://player.twitch.tv/?video=203449795&time=52m58s')
mnc3 = User.create!(username: 'olded', password: 'asdfasgasgetsdf', channel_id: mc.id, stream_title: 'Elite', stream_url: 'http://player.twitch.tv/?video=204262765&time=26m18s')
poe1 = User.create!(username: 'Ziz', password: 'mdrjydksfg', channel_id: poe.id, stream_title: 'mayhem SSFHC', stream_url: 'http://player.twitch.tv/?video=203975415&time=03h45m01s')
poe2 = User.create!(username: 'mathy', password: 'haerfndf', channel_id: poe.id, stream_title: 'mayhem race!', stream_url: 'http://player.twitch.tv/?video=204553113&time=39m01s')
poe3 = User.create!(username: 'ziggy', password: 'ndfhkdasd', channel_id: poe.id, stream_title: 'Depraved trinity', stream_url: 'http://player.twitch.tv/?video=204149916')
smo1 = User.create!(username: '720chrism', password: 'po2SYRtzfdac', channel_id: smo.id, stream_title: 'Super Mario Odyssey Speedrun!', stream_url: 'http://player.twitch.tv/?video=204862311&time=08m32s')
smo2 = User.create!(username: 'bluntgoku', password: 'tygasohkd', channel_id: smo.id, stream_title: 'Super Mario Odyssey Routing run', stream_url: 'http://player.twitch.tv/?video=205067607&time=25m20s')
smo3 = User.create!(username: 'trihard', password: 'mkfghksfgsdfhj', channel_id: smo.id, stream_title: 'any% runs', stream_url: 'http://player.twitch.tv/?video=204694427&time=24m38s')
btw1 = User.create!(username: 'grizzle', password: 'mdgffahsdfaj', channel_id: botw.id, stream_title: '1st time playthrough', stream_url: 'http://player.twitch.tv/?video=202106698&time=46m28s')
btw2 = User.create!(username: 'afro', password: 'njsgfksdfgsad', channel_id: botw.id, stream_title: 'friday night', stream_url: 'http://player.twitch.tv/?video=204037665&time=03h51m10s')
btw3 = User.create!(username: 'rails db:drop', password: 'hmadfgasdf', channel_id: botw.id, stream_title: 'casual 100%', stream_url: 'http://player.twitch.tv/?video=204151564&time=27m16s')
smt1 = User.create!(username: 'brundon', password: 'hqaeajfg4brw', channel_id: smite.id, stream_title: 'Force pick customs', stream_url: 'http://player.twitch.tv/?video=204737448&time=42m02s')
smt2 = User.create!(username: 'fish', password: 'asfjAFSasdf', channel_id: smite.id, stream_title: 'relearning smite', stream_url: 'http://player.twitch.tv/?video=203409294&time=41m32s')
smt3 = User.create!(username: 'liferunner', password: 'afnagfsadf', channel_id: smite.id, stream_title: 'ranked maybe', stream_url: 'http://player.twitch.tv/?video=204278955&time=2h52m25s')
rss1 = User.create!(username: 'dingusparty', password: 'mkasfdgfsdjgsdt', channel_id: rss.id, stream_title: 'I am become potato, destroyer of aim', stream_url: 'http://player.twitch.tv/?video=203059316&time=23m59s')
rss2 = User.create!(username: 'Ubisports', password: 'hasdfanasefasdf', channel_id: rss.id, stream_title: 'Season 2', stream_url: 'http://player.twitch.tv/?video=204485209&time=01h37m30s')
rss3 = User.create!(username: 'starrykix', password: 'asdsfjasdfasdf', channel_id: rss.id, stream_title: 'pewpew', stream_url: 'http://player.twitch.tv/?video=204027622&time=39m10s')
rol1 = User.create!(username: 'rocketlag', password: 'asdhasdfasdf', channel_id: rl.id, stream_title: 'EU Promotion Tournament', stream_url: 'http://player.twitch.tv/?video=186595606&time=32s')
rol2 = User.create!(username: 'squishymuffins', password: 'asdhasdfasdb', channel_id: rl.id, stream_title: 'place', stream_url: 'http://player.twitch.tv/?video=204589291&time=08m32s')
rol3 = User.create!(username: 'daycop', password: 'fhscvasd', channel_id: rl.id, stream_title: 'Gale Force Esports', stream_url: 'http://player.twitch.tv/?video=204499385&time=08m32s')
ssb1 = User.create!(username: 'nario', password: 'po2asdfasdfsSYRtzfdasdbac', channel_id: ssb4.id, stream_title: 'IRONMAN', stream_url: 'http://player.twitch.tv/?video=203575209&time=05h02m10s')
ssb2 = User.create!(username: 'unrivaledtournaments', password: 'asdbasfbsf', channel_id: ssb4.id, stream_title: 'ignition!', stream_url: 'http://player.twitch.tv/?video=204220487&time=02h38m40s')
ssb3 = User.create!(username: 'events', password: 'naefga', channel_id: ssb4.id, stream_title: 'midwest mayhem', stream_url: 'http://player.twitch.tv/?video=204216956')
ssm1 = User.create!(username: 'mango', password: 'tewtrwgwr', channel_id: ssbm.id, stream_title: 'melee', stream_url: 'http://player.twitch.tv/?video=203522033&time=01h12m20s')
ssm2 = User.create!(username: 'leffen', password: 'tyhjsdg', channel_id: ssbm.id, stream_title: 'fighting games', stream_url: 'http://player.twitch.tv/?video=204853377&time=02h17m30s')
ssm3 = User.create!(username: 'hangrybox', password: 'ghjkgfjkft', channel_id: ssbm.id, stream_title: 'brief stream', stream_url: 'http://player.twitch.tv/?video=201753973&time=17m50s')
oot1 = User.create!(username: 'zfg', password: 'rqerhsdfba', channel_id: oot.id, stream_title: 'new route testing', stream_url: 'http://player.twitch.tv/?video=204809404&time=18m32s')
oot2 = User.create!(username: 'cheese', password: 'asdfraefasd', channel_id: oot.id, stream_title: '100% runs', stream_url: 'http://player.twitch.tv/?video=204425438&time=20m32s')
oot3 = User.create!(username: 'clunt', password: 'sdthjsdfa', channel_id: oot.id, stream_title: 'Oot 100% PB', stream_url: 'http://player.twitch.tv/?video=108909134&time=42m30s')
